import Head from 'next/head'

import FrontendLoader from '../components/FrontendLoader';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Dashboard</h1>

      <hr />

      <FrontendLoader id="internal-frontend-app" />
    </>
  )
}
